##########################
#                        #
#   Discord Bot Config   #
#                        #
###########################

enabled: true
token: "bot token here"
automodChannelId: "0"
automodMcChannelId: "0"
modLogChannelId: "0"
chatMcLogChannelId: "0"
autoroleId: "0"
reportsChannelId: "0"
statusesBot: ["Discord API!","ReonCore Plugin","github.com/ReoGroup/ReonCore"]
loadingStatus: "loading..."
# Change rich presence action. Playing, Watching and other.
statusType: "WATCHING"
status: "ONLINE"

##########################
#                        #
#    Minecraft Config    #
#                        #
###########################